export {
  computeFrictionMatrix,
  diversifyFrictionFindings,
  FRICTION_MATRIX_MAX_FINDINGS,
  FRICTION_MAX_FINDINGS_PER_SUBJECT,
  FRICTION_MIN_COACH_FINDINGS,
  FRICTION_MIN_DEVIATION_PCT,
  FRICTION_MIN_H2H_GAMES,
  FRICTION_MIN_H2H_GAMES_NFL,
  frictionMinHeadToHeadGames,
  getFrictionMatrixDataset,
  isFrictionMatrixLeague,
  resolveFrictionSubjectTeam,
  scanFrictionGrudgeMatrix,
  type FrictionGrudgeFinding,
  type FrictionMatrixDataset,
  type FrictionOfficialBundle,
  type FrictionPersonnelType,
  type PlayerFrictionPattern,
} from "@/lib/friction-matrix";
