/** Generated by scripts/copy-data-to-public.ts — do not edit. */
export type LeagueHeroStatsSnapshot = {
  officials: number;
  games: number;
  seasonSpan: string;
};

export const LEAGUE_HERO_STATS: Record<string, LeagueHeroStatsSnapshot> = {
  "nba": {
    "officials": 53,
    "games": 12301,
    "seasonSpan": "2016-2026"
  },
  "nfl": {
    "officials": 208,
    "games": 2757,
    "seasonSpan": "2016-2026"
  },
  "nhl": {
    "officials": 123,
    "games": 12282,
    "seasonSpan": "2016-2026"
  },
  "epl": {
    "officials": 48,
    "games": 3800,
    "seasonSpan": "2016-2026"
  },
  "laliga": {
    "officials": 33,
    "games": 1546,
    "seasonSpan": "2021-2026"
  },
  "cbb": {
    "officials": 515,
    "games": 9705,
    "seasonSpan": "2020-2026"
  },
  "cfb": {
    "officials": 0,
    "games": 1426,
    "seasonSpan": "2020-2026"
  }
};
