/** Generated by scripts/copy-data-to-public.ts — do not edit. */
export type LeagueHeroStatsSnapshot = {
  officials: number;
  games: number;
  seasonSpan: string;
};

export const LEAGUE_HERO_STATS: Record<string, LeagueHeroStatsSnapshot> = {
  "nba": {
    "officials": 109,
    "games": 11979,
    "seasonSpan": "Last 10 seasons"
  },
  "nfl": {
    "officials": 211,
    "games": 2757,
    "seasonSpan": "Last 10 seasons"
  },
  "nhl": {
    "officials": 123,
    "games": 12282,
    "seasonSpan": "Last 10 seasons"
  },
  "epl": {
    "officials": 48,
    "games": 3800,
    "seasonSpan": "Last 10 seasons"
  },
  "laliga": {
    "officials": 33,
    "games": 1546,
    "seasonSpan": "Last 5 seasons"
  }
};
