/** Generated by scripts/copy-data-to-public.ts — do not edit. */
export type LeagueHeroStatsSnapshot = {
  officials: number;
  games: number;
  seasonSpan: string;
};

export const LEAGUE_HERO_STATS: Record<string, LeagueHeroStatsSnapshot> = {
  "nba": {
    "officials": 53,
    "games": 12301,
    "seasonSpan": "Last 10 seasons"
  },
  "nfl": {
    "officials": 259,
    "games": 6825,
    "seasonSpan": "Last 26 seasons"
  },
  "nhl": {
    "officials": 123,
    "games": 12282,
    "seasonSpan": "Last 10 seasons"
  },
  "epl": {
    "officials": 48,
    "games": 3800,
    "seasonSpan": "Last 10 seasons"
  },
  "laliga": {
    "officials": 33,
    "games": 1546,
    "seasonSpan": "Last 5 seasons"
  },
  "cbb": {
    "officials": 287,
    "games": 2610,
    "seasonSpan": "Last 6 seasons"
  },
  "cfb": {
    "officials": 98,
    "games": 1166,
    "seasonSpan": "Last 6 seasons"
  }
};
